#:schema node_modules/wrangler/config-schema.json
name = "priyannikloginms"
main = "src/index.js"
compatibility_date = "2024-11-27"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "LOGIN_MS_KV"
id = "b894e2ca4e9f44dbafa2dd79d4b92d06"
